services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # backend:
  #   build:
  #     context: ./backend/base
  #     dockerfile: Dockerfile
  #   command: python manage.py runserver 0.0.0.0:8000
  #   container_name: django-backend
  #   volumes:
  #     - ./backend/base:/app
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - .env
  #   entrypoint: ["/app/entrypoint.sh"]
  #   depends_on:
  #     - db

  # frontend:
  #   build:
  #     context: ./frontend/blog
  #     dockerfile: Dockerfile
  #   command: sh -c "yarn build && yarn start"
  #   container_name: nextjs-frontend
  #   volumes:
  #     - ./frontend/blog:/app
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - backend

volumes:
  postgres_data:
