# Generated by Django 5.1 on 2025-01-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='fullname',
            new_name='username',
        ),
    ]
