# Generated by Django 5.1 on 2025-01-04 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_fullname_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='username',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='photo',
        ),
    ]
