# Generated by Django 5.1 on 2025-01-05 18:13

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_username_customuser_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.get_avatar_upload_to),
        ),
    ]
