export const posts = [
  {
    image: "/images/image1.jpg",
    title: "Post Title 1",
    created_at: "2025-01-03T10:00:00Z",
    description: "This is a description of the first post.",
    tags: ["IT", "Design", "Web Development"],
  },
  {
    image: "/images/image2.jpg",
    title: "Post Title 2",
    created_at: "2025-01-02T14:30:00Z",
    description: "This is a description of the second post.",
    tags: ["Design", "UI/UX", "Technology"],
  },
  {
    image: "/images/image3.jpg",
    title: "Post Title 3",
    created_at: "2025-01-01T08:45:00Z",
    description: "This is a description of the third post.",
    tags: ["Development", "Programming", "React"],
  },
  {
    image: "/images/image1.jpg",
    title: "Post Title 1",
    created_at: "2025-01-03T10:00:00Z",
    description: "This is a description of the first post.",
    tags: ["IT", "Design", "Web Development"],
  },
  {
    image: "/images/image2.jpg",
    title: "Post Title 2",
    created_at: "2025-01-02T14:30:00Z",
    description: "This is a description of the second post.",
    tags: ["Design", "UI/UX", "Technology"],
  },
  {
    image: "/images/image3.jpg",
    title: "Post Title 3",
    created_at: "2025-01-01T08:45:00Z",
    description: "This is a description of the third post.",
    tags: ["Development", "Programming", "React"],
  },
  {
    image: "/images/image1.jpg",
    title: "Post Title 1",
    created_at: "2025-01-03T10:00:00Z",
    description: "This is a description of the first post.",
    tags: ["IT", "Design", "Web Development"],
  },
  {
    image: "/images/image2.jpg",
    title: "Post Title 2",
    created_at: "2025-01-02T14:30:00Z",
    description: "This is a description of the second post.",
    tags: ["Design", "UI/UX", "Technology"],
  },
  {
    image: "/images/image3.jpg",
    title: "Post Title 3",
    created_at: "2025-01-01T08:45:00Z",
    description: "This is a description of the third post.",
    tags: ["Development", "Programming", "React"],
  },
];
